extends SceneTree
# Reads data/monsters.csv and writes docs/monster-balance.md: every monster at
# the depth it is met, each tier's elemental coverage, and a list of warnings
# against the rules the roster is meant to keep. From the repo root:
#
#   godot --headless --path . --script tools/monster_report.gd
#
# It reads the CSV, not Enemy's tables, so an edited sheet can be checked before
# anything in the game changes. Levels, stats and HP use the game's own
# formulas (Enemy.level_for_floor, the 0.22 stat scale, lv*10 + def*3).

const IN: String = "res://data/monsters.csv"
const OUT: String = "res://docs/monster-balance.md"

const ELEMENTS: Array[String] = ["phys", "fire", "ice", "thunder", "light", "dark"]
const DAMAGE: Array[String] = ["phys", "fire", "ice", "thunder"]
const BLOCKS: Array[String] = ["null", "reflect", "drain"]
const STATES: Array[String] = ["weak", "resist", "null", "reflect", "drain"]
const TIER_NAMES: Array[String] = ["I", "II", "III", "IV"]

# What the run starts holding: a swing and Ember.
const STARTING_KIT: Array[String] = ["phys", "fire"]

var rows: Array[Dictionary] = []
var warnings: Array[String] = []
var notes: Array[String] = []


func _initialize() -> void:
	_read()
	var md: Array[String] = []
	md.append("# Monster balance report")
	md.append("")
	md.append("Generated by `tools/monster_report.gd` from `data/monsters.csv`. Levels, stats "
			+ "and HP are what the game builds at the depth each monster is met. Tier monsters are "
			+ "shown at the first floor of their band. Chart letters are the battle chart's: "
			+ "W weak, S strong (resists), N null, R reflect, D drain.")
	md.append("")
	for tier: int in range(1, 5):
		_check_tier(tier)
	_check_dragons()
	md.append("## Warnings (%d)" % warnings.size())
	md.append("")
	md.append("Things that break a rule the roster is meant to keep.")
	md.append("")
	for w: String in warnings:
		md.append("- " + w)
	if warnings.is_empty():
		md.append("- None.")
	md.append("")
	md.append("## Notes (%d)" % notes.size())
	md.append("")
	md.append("Worth a look, not necessarily wrong.")
	md.append("")
	for n: String in notes:
		md.append("- " + n)
	md.append("")
	md.append_array(_spread_section())
	for tier: int in range(1, 5):
		md.append_array(_tier_section(tier))
	md.append_array(_set_piece_section())
	var f: FileAccess = FileAccess.open(OUT, FileAccess.WRITE)
	f.store_string("\n".join(md) + "\n")
	f.close()
	print("%d monsters, %d warnings, %d notes -> %s" % [rows.size(), warnings.size(),
			notes.size(), OUT])
	quit()


func _read() -> void:
	var f: FileAccess = FileAccess.open(IN, FileAccess.READ)
	var header: PackedStringArray = f.get_csv_line()
	while not f.eof_reached():
		var line: PackedStringArray = f.get_csv_line()
		if line.size() < header.size() or line[0].strip_edges() == "":
			continue
		var r: Dictionary = {}
		for i: int in header.size():
			r[header[i].strip_edges()] = line[i].strip_edges()
		rows.append(r)


# ── Building a monster the way the game does ─────────────────────────────────

func _level(r: Dictionary, floor_num: int) -> int:
	match r["group"]:
		"warden":
			return maxi(2, roundi(float(floor_num) * 1.75))
		"dragon":
			return maxi(2, floor_num * 2)
	return Enemy.level_for_floor(floor_num, int(r.get("rank", "0")))


func _stats(r: Dictionary, floor_num: int) -> Dictionary:
	var lv: int = _level(r, floor_num)
	var scale: float = 1.0 + float(lv - 1) * 0.22
	var s: Dictionary = {lv = lv}
	for k: String in ["str", "def", "mag", "agl"]:
		s[k] = maxi(0 if k == "mag" else 1, roundi(float(r[k]) * scale))
	var hp: int = lv * 10 + int(s["def"]) * 3
	if r["group"] == "dragon":
		hp *= Enemy.BOSS_HP_MULT
	elif r["group"] == "monster":
		hp = maxi(1, roundi(float(hp) * Enemy.opening_hp_scale(floor_num)))
	s["hp"] = hp
	return s


func _first_floor(tier: int) -> int:
	return (tier - 1) * Level.BOSS_EVERY + 1


func _floor_of(r: Dictionary) -> int:
	var where: String = r.get("where", "")
	var digits: String = ""
	for ch: String in where:
		if ch.is_valid_int():
			digits += ch
		elif digits != "":
			break
	return int(digits) if digits != "" else 1


func _tier_rows(tier: int) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for r: Dictionary in rows:
		if r["group"] == "monster" and int(r["tier"]) == tier:
			out.append(r)
	return out


# Which of the six the player can have in hand by a floor. The three damage
# lines are sold from floor 1; banishing opens at 3 (Item.ELEMENTAL_SCROLLS).
func _available(floor_num: int) -> Array[String]:
	var out: Array[String] = ["phys"]
	for spell_id: String in Item.ELEMENTAL_SCROLLS:
		if int(Item.ELEMENTAL_SCROLLS[spell_id]) <= floor_num:
			var el: String = Spell.get_data(spell_id).get("element", "") as String
			if el != "" and el not in out:
				out.append(el)
	return out


# ── Rules ─────────────────────────────────────────────────────────────────────

func _check_tier(tier: int) -> void:
	var tr: Array[Dictionary] = _tier_rows(tier)
	var tn: String = "Tier %s" % TIER_NAMES[tier - 1]
	if tr.is_empty():
		warnings.append("%s has no monsters." % tn)
		return
	# A band is four floors of random packs drawn from this list alone.
	if tr.size() < 5:
		warnings.append("%s has only %d monster types (%s) for its four floors." % [
				tn, tr.size(), ", ".join(tr.map(func(r): return r["name"]))])

	# Every damage line has something in the band it lands hard on.
	for el: String in DAMAGE:
		var weak: int = 0
		for r: Dictionary in tr:
			if r[el] == "weak":
				weak += 1
		if weak == 0:
			warnings.append("%s: nothing is weak to **%s**." % [tn, el])

	# The opening floors are the player's swing and Ember and nothing else.
	if tier == 1:
		for r: Dictionary in tr:
			for el: String in STARTING_KIT:
				if r[el] in BLOCKS:
					warnings.append("%s: **%s** %ss %s — the starting kit, on the opening floors." % [
							tn, r["name"], r[el], el])
				elif r[el] == "resist":
					notes.append("%s: %s resists %s, part of the starting kit." % [tn, r["name"], el])

	# No line the player can hold should be walled off by most of the band.
	for el: String in _available(_first_floor(tier)):
		var blocked: int = 0
		for r: Dictionary in tr:
			if r[el] in BLOCKS:
				blocked += 1
		if blocked * 3 > tr.size():
			warnings.append("%s: %d of %d monsters null, reflect or drain **%s**." % [
					tn, blocked, tr.size(), el])

	# Ailments and casters.
	var ail: int = 0
	var casters: int = 0
	var personalities: Dictionary = {}
	for r: Dictionary in tr:
		if r["ailment"] != "":
			ail += 1
		if r["caster"] == "yes":
			casters += 1
		if r["personality"] != "":
			personalities[r["personality"]] = true
	if ail == 0:
		warnings.append("%s: nothing inflicts an ailment." % tn)
	if casters * 2 > tr.size():
		notes.append("%s: %d of %d monsters are casters." % [tn, casters, tr.size()])
	if personalities.size() < 2:
		warnings.append("%s: only %d talk personality (%s), so reading a temper teaches nothing." % [
				tn, personalities.size(), ", ".join(personalities.keys())])

	# Stat outliers against the band's median, at its first floor.
	var at: int = _first_floor(tier)
	for k: String in ["hp", "str", "mag", "agl"]:
		var vals: Array[float] = []
		for r: Dictionary in tr:
			vals.append(float(_stats(r, at)[k]))
		var sorted: Array[float] = vals.duplicate()
		sorted.sort()
		var med: float = sorted[sorted.size() / 2]
		if med <= 0.0:
			continue
		for i: int in tr.size():
			var ratio: float = vals[i] / med
			if ratio >= 1.45:
				notes.append("%s: %s's %s is %.0f, %.1fx the band's median (%.0f)." % [
						tn, tr[i]["name"], k.to_upper(), vals[i], ratio, med])
			elif ratio <= 0.6 and not (k == "mag" and tr[i]["attacks"] == ""):
				notes.append("%s: %s's %s is %.0f, only %.1fx the band's median (%.0f)." % [
						tn, tr[i]["name"], k.to_upper(), vals[i], ratio, med])

	# Monsters that read the same.
	var seen: Dictionary = {}
	for r: Dictionary in tr:
		var sig: String = "|".join(ELEMENTS.map(func(e): return r[e]))
		if seen.has(sig):
			notes.append("%s: %s has the same chart as %s." % [tn, r["name"], seen[sig]])
		else:
			seen[sig] = r["name"]
		var has_weak: bool = false
		for el: String in ELEMENTS:
			if r[el] == "weak":
				has_weak = true
		if not has_weak:
			notes.append("%s: %s has no weakness at all." % [tn, r["name"]])
		for el: String in (r["attacks"] as String).split(" ", false):
			if r.get(el, "") == "weak":
				notes.append("%s: %s attacks with %s and is weak to it." % [tn, r["name"], el])


# Each dragon should answer to something the party can bring by then: a spell
# on the shelf, and ideally a recruit from the bands before it.
func _check_dragons() -> void:
	for r: Dictionary in rows:
		if r["group"] != "dragon":
			continue
		var fl: int = _floor_of(r)
		var weak: Array[String] = []
		for el: String in ELEMENTS:
			if r[el] == "weak":
				weak.append(el)
		if weak.is_empty():
			warnings.append("**%s** has no weakness." % r["name"])
			continue
		for el: String in weak:
			if el not in _available(fl):
				warnings.append("**%s** is weak to %s, which the player cannot hold by floor %d." % [
						r["name"], el, fl])
			var recruits: Array[String] = []
			for m: Dictionary in rows:
				if m["group"] == "monster" and _first_floor(int(m["tier"])) < fl \
						and el in (m["attacks"] as String).split(" ", false):
					recruits.append(m["name"])
			if recruits.is_empty():
				notes.append("%s is weak to %s, but no monster met before floor %d attacks with it." % [
						r["name"], el, fl])
		for el: String in STARTING_KIT:
			if r[el] in BLOCKS:
				notes.append("%s %ss %s, part of the starting kit." % [r["name"], r[el], el])


# ── Tables ────────────────────────────────────────────────────────────────────

func _chart(r: Dictionary) -> String:
	# The letters the battle chart uses: S for strong, R for reflect.
	var letter: Dictionary = {"weak": "W", "resist": "S", "null": "N", "reflect": "R", "drain": "D"}
	var parts: Array[String] = []
	for el: String in ELEMENTS:
		if r[el] != "":
			parts.append("%s %s" % [el.capitalize(), letter.get(r[el], "?")])
	return " · ".join(parts) if not parts.is_empty() else "—"


func _tier_section(tier: int) -> Array[String]:
	var tr: Array[Dictionary] = _tier_rows(tier)
	var at: int = _first_floor(tier)
	var md: Array[String] = []
	md.append("## Tier %s — floors %d-%d (shown at floor %d)" % [TIER_NAMES[tier - 1], at,
			at + Level.BOSS_EVERY - 2, at])
	md.append("")
	md.append("| Element | Weak | Resist | Null | Reflect | Drain |")
	md.append("|---|---|---|---|---|---|")
	for el: String in ELEMENTS:
		var counts: Array[String] = []
		for st: String in STATES:
			var c: int = 0
			for r: Dictionary in tr:
				if r[el] == st:
					c += 1
			counts.append(str(c) if c > 0 else "·")
		md.append("| %s | %s |" % [el.capitalize(), " | ".join(counts)])
	md.append("")
	md.append("| Monster | LV | HP | STR | MAG | AGL | Chart | Attacks | Ailment | Temper |")
	md.append("|---|---|---|---|---|---|---|---|---|---|")
	for r: Dictionary in tr:
		var s: Dictionary = _stats(r, at)
		md.append("| %s | %d | %d | %d | %d | %d | %s | %s | %s | %s |" % [
				r["name"], s["lv"], s["hp"], s["str"], s["mag"], s["agl"], _chart(r),
				(r["attacks"] + (" (" + r["reach"] + ")" if r["attacks"] != "" else "")) \
						if r["attacks"] != "" else "—",
				r["ailment"] if r["ailment"] != "" else "—",
				r["personality"]])
	md.append("")
	return md


func _set_piece_section() -> Array[String]:
	var md: Array[String] = []
	md.append("## Wardens, the Mimic and the dragons")
	md.append("")
	md.append("| Monster | Where | LV | HP | STR | MAG | AGL | Chart | Attacks | Ailment |")
	md.append("|---|---|---|---|---|---|---|---|---|---|")
	for r: Dictionary in rows:
		if r["group"] == "monster":
			continue
		var fl: int = _floor_of(r)
		var s: Dictionary = _stats(r, fl)
		md.append("| %s | %s | %d | %d | %d | %d | %d | %s | %s | %s |" % [
				r["name"], r["where"], s["lv"], s["hp"], s["str"], s["mag"], s["agl"],
				_chart(r), r["attacks"] if r["attacks"] != "" else "—",
				r["ailment"] if r["ailment"] != "" else "—"])
	md.append("")
	return md


# ── Spread ────────────────────────────────────────────────────────────────────
#
# How the elements are shared out over the roaming roster as a whole: how many
# monsters answer each element each way, how many attack with it, and how many
# weaknesses, blocks and attack lines a monster tends to carry.

func _roamers() -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for r: Dictionary in rows:
		if r["group"] == "monster":
			out.append(r)
	return out


func _attacks_of(r: Dictionary) -> PackedStringArray:
	return (r["attacks"] as String).split(" ", false)


func _spread_section() -> Array[String]:
	var ms: Array[Dictionary] = _roamers()
	var md: Array[String] = []
	md.append("## Element spread (%d roaming monsters)" % ms.size())
	md.append("")
	md.append("How many monsters answer each element each way, and how many attack with it.")
	md.append("")
	md.append("| Element | Weak | Resist | Null | Reflect | Drain | Normal | Attack with it |")
	md.append("|---|---|---|---|---|---|---|---|")
	for el: String in ELEMENTS:
		var cells: Array[String] = []
		var normal: int = 0
		for st: String in STATES:
			var c: int = 0
			for r: Dictionary in ms:
				if r[el] == st:
					c += 1
			cells.append(str(c))
		for r: Dictionary in ms:
			if r[el] == "":
				normal += 1
		var atk: int = 0
		for r: Dictionary in ms:
			if el in _attacks_of(r):
				atk += 1
		md.append("| %s | %s | %d | %d |" % [el.capitalize(), " | ".join(cells), normal, atk])
	md.append("")

	# Per tier, who attacks with what: the lines a recruit from that band brings.
	md.append("Attackers per element, by tier (what a recruit from that band can bring):")
	md.append("")
	md.append("| Tier | Phys only | Fire | Ice | Thunder | Light | Dark |")
	md.append("|---|---|---|---|---|---|---|")
	for tier: int in range(1, 5):
		var tr: Array[Dictionary] = _tier_rows(tier)
		var cells: Array[String] = []
		var phys_only: int = 0
		for r: Dictionary in tr:
			if _attacks_of(r).is_empty():
				phys_only += 1
		cells.append(str(phys_only))
		for el: String in ["fire", "ice", "thunder", "light", "dark"]:
			var c: int = 0
			for r: Dictionary in tr:
				if el in _attacks_of(r):
					c += 1
			cells.append(str(c) if c > 0 else "·")
		md.append("| %s (%d) | %s |" % [TIER_NAMES[tier - 1], tr.size(), " | ".join(cells)])
	md.append("")

	# How many of each a single monster carries.
	md.append("How much each monster carries — number of monsters with 0, 1, 2, 3+ of each:")
	md.append("")
	md.append("| Per monster | 0 | 1 | 2 | 3+ |")
	md.append("|---|---|---|---|---|")
	var measures: Array = [
		["Weaknesses", func(r: Dictionary) -> int: return ELEMENTS.filter(func(e): return r[e] == "weak").size()],
		["Resists", func(r: Dictionary) -> int: return ELEMENTS.filter(func(e): return r[e] == "resist").size()],
		["Blocks (null / reflect / drain)", func(r: Dictionary) -> int:
			return ELEMENTS.filter(func(e): return r[e] in BLOCKS).size()],
		["Attack elements", func(r: Dictionary) -> int: return _attacks_of(r).size()],
	]
	for m: Array in measures:
		var buckets: Array[int] = [0, 0, 0, 0]
		for r: Dictionary in ms:
			buckets[mini(3, (m[1] as Callable).call(r))] += 1
		md.append("| %s | %d | %d | %d | %d |" % [m[0], buckets[0], buckets[1], buckets[2], buckets[3]])
	md.append("")

	var tiers: Array[String] = []
	for tier: int in range(1, 5):
		tiers.append("%s: %d" % [TIER_NAMES[tier - 1], _tier_rows(tier).size()])
	md.append("Monsters per tier — %s." % ", ".join(tiers))
	md.append("")
	return md
